/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MModuleIdRouteImport } from './routes/m.$moduleId'
import { Route as MModuleIdSubIdRouteImport } from './routes/m.$moduleId.$subId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleIdRoute = MModuleIdRouteImport.update({
  id: '/m/$moduleId',
  path: '/m/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleIdSubIdRoute = MModuleIdSubIdRouteImport.update({
  id: '/$subId',
  path: '/$subId',
  getParentRoute: () => MModuleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/approvals': typeof ApprovalsRoute
  '/masters': typeof MastersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/m/$moduleId': typeof MModuleIdRouteWithChildren
  '/m/$moduleId/$subId': typeof MModuleIdSubIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/approvals': typeof ApprovalsRoute
  '/masters': typeof MastersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/m/$moduleId': typeof MModuleIdRouteWithChildren
  '/m/$moduleId/$subId': typeof MModuleIdSubIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/approvals': typeof ApprovalsRoute
  '/masters': typeof MastersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/m/$moduleId': typeof MModuleIdRouteWithChildren
  '/m/$moduleId/$subId': typeof MModuleIdSubIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/approvals'
    | '/masters'
    | '/reports'
    | '/settings'
    | '/m/$moduleId'
    | '/m/$moduleId/$subId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/approvals'
    | '/masters'
    | '/reports'
    | '/settings'
    | '/m/$moduleId'
    | '/m/$moduleId/$subId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/approvals'
    | '/masters'
    | '/reports'
    | '/settings'
    | '/m/$moduleId'
    | '/m/$moduleId/$subId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  MastersRoute: typeof MastersRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  MModuleIdRoute: typeof MModuleIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$moduleId': {
      id: '/m/$moduleId'
      path: '/m/$moduleId'
      fullPath: '/m/$moduleId'
      preLoaderRoute: typeof MModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$moduleId/$subId': {
      id: '/m/$moduleId/$subId'
      path: '/$subId'
      fullPath: '/m/$moduleId/$subId'
      preLoaderRoute: typeof MModuleIdSubIdRouteImport
      parentRoute: typeof MModuleIdRoute
    }
  }
}

interface MModuleIdRouteChildren {
  MModuleIdSubIdRoute: typeof MModuleIdSubIdRoute
}

const MModuleIdRouteChildren: MModuleIdRouteChildren = {
  MModuleIdSubIdRoute: MModuleIdSubIdRoute,
}

const MModuleIdRouteWithChildren = MModuleIdRoute._addFileChildren(
  MModuleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ApprovalsRoute: ApprovalsRoute,
  MastersRoute: MastersRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  MModuleIdRoute: MModuleIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
